import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const appPath = resolve(process.cwd(), 'src/ui/App.tsx')
const mountPath = resolve(process.cwd(), 'src/ui/GameMount.tsx')
const enginePath = resolve(process.cwd(), 'src/game/engine.ts')
const src = readFileSync(appPath, 'utf8')
const mountSrc = readFileSync(mountPath, 'utf8')
const engineSrc = readFileSync(enginePath, 'utf8')

const checks = [
  ["shared helper: random seed", "function randomSeed(){"],
  ["shared helper: random class/race", "function randomClassRace(){"],
  ["shared helper: resolve chosen seed", "function resolveChosenSeed(seedInput:string){"],
  ["shared helper: apply preset to create", "const applyPresetToCreate = (preset:{klass:PlayerClass,race:PlayerRace,seed:number|string}, label:'Daily'|'Last-run')=>{"],
  ["shared helper: apply daily preset", "const applyDailyPresetToCreate = ()=>{"],
  ["shared helper: apply last-run preset", "const applyLastRunPresetToCreate = ()=>{"],
  ["shared helper: apply random class/race in create", "const applyRandomClassRaceToCreate = (withSeed=false)=>{"],
  ["shared helper: open create preset", "const openCreatePreset = (preset:{klass:PlayerClass,race:PlayerRace,seed:number|string})=>{"],
  ["shared helper: launch preset game", "const launchGamePreset = (preset:{klass:PlayerClass,race:PlayerRace,seed:number|string})=>{"],
  ["launch/create helpers preserve visual preset", "vis: visualPreset, contrast: visualPreset==='normal' ? 0 : 1"],
  ["shared helper: copy create launch link", "const copyCreateLaunchLink = async ()=>{"],
  ["create launch link helper: uses resolved seed", "buildShareLink(resolveChosenSeed(customSeed), klass, race)"],
  ["menu hotkey: Z daily build", "if(ev.key==='z' || ev.key==='Z') openCreatePreset({klass:dailyPreset.klass, race:dailyPreset.race, seed:dailyPreset.seed})"],
  ["menu hotkey: D daily challenge", "if(ev.key==='d' || ev.key==='D') launchGamePreset({klass:dailyPreset.klass, race:dailyPreset.race, seed:dailyPreset.seed})"],
  ["menu button: daily challenge uses launcher", "<button onClick={()=>launchGamePreset({klass:dailyPreset.klass, race:dailyPreset.race, seed:dailyPreset.seed})} title='D · launch daily challenge now'>Daily Challenge"],
  ["menu hotkey: H primer alias", "if(ev.key==='h' || ev.key==='H') toggleMenuModal('primer')"],
  ["menu hotkey: V copy daily preset", "if(ev.key==='v' || ev.key==='V') copyDailyPreset()"],
  ["menu hotkey: F toggle damage numbers", "if(ev.key==='f' || ev.key==='F') toggleFloatingNumbers()"],
  ["menu hotkey: G last build", "if((ev.key==='g' || ev.key==='G') && lastRun) openCreatePreset({klass:lastRun.klass, race:lastRun.race, seed:lastRun.seed})"],
  ["menu action: last build button", ">Last Build</button>"],
  ["menu button: last build uses create helper", "<button onClick={()=>openCreatePreset({klass:lastRun.klass, race:lastRun.race, seed:lastRun.seed})} title='G · prefill create from last run'>Last Build</button>"],
  ["menu button: daily build uses create helper", "<button onClick={()=>openCreatePreset({klass:dailyPreset.klass, race:dailyPreset.race, seed:dailyPreset.seed})} title='Z · prefill create from daily preset'>Daily Build</button>"],
  ["menu button: resume last uses launcher", "<button onClick={()=>launchGamePreset({klass:lastRun.klass, race:lastRun.race, seed:lastRun.seed})} title='Y · relaunch last snapshot'>Resume Last Run</button>"],
  ["menu tooltip: quick start intent", "title='A · random class/race/seed'"],
  ["hotkey: A quick start uses launcher", "if(ev.key==='a' || ev.key==='A'){\n        const rr = randomClassRace()\n        launchGamePreset({klass:rr.klass, race:rr.race, seed:randomSeed()})\n      }"],
  ["menu tooltip: daily challenge intent", "title='D · launch daily challenge now'"],
  ["menu action: damage numbers toggle button", "<button onClick={toggleFloatingNumbers} title='F'>Damage Numbers:"],
  ["menu hotkeys mention visual-preserving links", "I Copy Links (preserves Visual)"],
  ["run header mentions visual-preserving copy link", "V copy link (preserves Visual)"],
  ["share link helper exists", "const buildShareLink = (seedValue:string|number, classValue:PlayerClass, raceValue:PlayerRace)=>{"],
  ["copy run link preserves visual preset", "u.searchParams.set('vis', visualPreset)"],
  ["copy run link preserves contrast flag", "u.searchParams.set('contrast', visualPreset==='normal' ? '0' : '1')"],
  ["link bundle uses share helper", "links.push(`daily=${buildShareLink(dailyPreset.seed, dailyPreset.klass, dailyPreset.race)}`)"],
  ["visual link hint helper exists", "const visualLinkHint = 'includes current Visual mode'"],
  ["visual keyed hint helper exists", "const visualLinkHintKeyed = (key:string)=> `${key} · ${visualLinkHint}`"],
  ["copy run link ui hint uses helper", "title={visualLinkHint}"],
  ["copy bundle ui hint uses keyed helper", "title={visualLinkHintKeyed('I')}"],
  ["copy daily-link ui hint uses keyed helper", "title={visualLinkHintKeyed('J')}"],
  ["copy status helper exists", "const visualModeStatus = (prefix:string)=> `${prefix} (Visual: ${visualPresetLabel}).`"],
  ["copy run link status uses helper", "setStatus(visualModeStatus('Run link copied'))"],
  ["copy create launch status uses helper", "setStatus(visualModeStatus('Create launch link copied'))"],
  ["copy last-run link status uses helper", "setStatus(visualModeStatus('Last run link copied'))"],
  ["copy daily link status uses helper", "setStatus(visualModeStatus('Daily challenge link copied'))"],
  ["copy link bundle status uses helper", "setStatus(visualModeStatus('Link bundle copied'))"],
  ["visual preset helper exists", "function getVisualPresetFromUrl(): VisualPreset"],
  ["visual preset default readable", "return getParams().get('contrast') === '0' ? 'normal' : 'readable'"],
  ["create hotkey: R reroll build+seed", "if(ev.key==='r' || ev.key==='R'){"],
  ["create status: surprise feedback", "setStatus('Surprise class/race applied.')"],
  ["create status: reroll feedback", "setStatus('Rerolled class, race, and seed.')"],
  ["create action: reroll build+seed button", ">Reroll Build+Seed</button>"],
  ["create tooltip: surprise intent", "title='S · randomize class/race only'"],
  ["create tooltip: quickstart intent", "title='A · random build + seed and launch'"],
  ["create button: quick start uses launcher", "title='A · random build + seed and launch'>Quick Start</button>"],
  ["create hint: J launch-link shown", "J copy launch link"],
  ["create hint: back alias shown", "B/Esc back"],
  ["create hotkey: J copy launch link", "if(ev.key==='j' || ev.key==='J') copyCreateLaunchLink()"],
  ["create button tooltip: back alias", "title='B / Esc'>Back</button>"],
  ["create hotkey: Y apply last run", "if((ev.key==='y' || ev.key==='Y') && lastRun) applyLastRunPresetToCreate()"],
  ["create hotkey: L start last run", "if((ev.key==='l' || ev.key==='L') && lastRun) launchGamePreset({klass:lastRun.klass, race:lastRun.race, seed:lastRun.seed})"],
  ["create hotkey: B back to menu", "if(ev.key==='Escape' || ev.key==='b' || ev.key==='B') navigate({screen:'menu'})"],
  ["create action: start daily preset button", ">Start Daily Preset</button>"],
  ["create tooltip: start daily preset intent", "title='D · launch daily preset now'"],
  ["create tooltip: start last-run preset intent", "title='L · launch last-run preset now'"],
  ["create button: copy launch link", "title='J · copy run link for current create setup'>Copy Launch Link</button>"],
  ["create start-adventure button uses launcher", "launchGamePreset({klass, race, seed:resolveChosenSeed(customSeed)})"],
  ["daily row action: open build", ">Open Build</button>"],
  ["daily row tooltip: open build intent", "title='Z · open daily build in create'"],
  ["records action: play daily", ">Play Daily Challenge</button>"],
  ["records button: play daily uses launcher", "title='D · launch daily challenge immediately from records' onClick={()=>launchGamePreset({klass:dailyPreset.klass, race:dailyPreset.race, seed:dailyPreset.seed})}"],
  ["records tooltip: play daily intent", "title='D · launch daily challenge immediately from records'"],
  ["records action: open daily in create", ">Open Daily in Create</button>"],
  ["records button: open daily in create uses helper", "title='Z · prefill create with daily loadout' onClick={()=>openCreatePreset({klass:dailyPreset.klass, race:dailyPreset.race, seed:dailyPreset.seed})}"],
  ["records button: open-last in create uses helper", "{lastRun && <button title='G · prefill create with last-run loadout' onClick={()=>openCreatePreset({klass:lastRun.klass, race:lastRun.race, seed:lastRun.seed})}>Open Last in Create</button>}"],
  ["records button: resume-last uses launcher", "{lastRun && <button title='Y' onClick={()=>launchGamePreset({klass:lastRun.klass, race:lastRun.race, seed:lastRun.seed})}>Resume Last Run</button>}"],
  ["records hint strip", "Quick keys:"],
  ["records quick-keys mention visual-preserving link bundle", "I link bundle (preserves Visual)"],
  ["run primer visual mode hint", "Visual mode: <b>Readable</b> default, <b>Crisp</b> for max tactical clarity, <b>Normal</b> for mood."],
  ["patch notes visual preset bullet", "Visual presets: Normal / Readable / Crisp (Readable is now default)"],
  ["renderer fallback state", "const [showRendererFallback,setShowRendererFallback] = useState(false)"],
  ["renderer fallback delayed", "const t = window.setTimeout(()=>setShowRendererFallback(true), 1600)"],
  ["renderer fallback retry button", "Renderer still initializing… <button onClick={retryRenderer}"],
  ["game hotkey auto-equip", "if(ev.key==='x' || ev.key==='X') (window as any).game?.autoEquipBest?.()"],
  ["game hotkey sort inventory", "if(ev.key==='z' || ev.key==='Z') (window as any).game?.sortInventory?.()"],
  ["game hotkey unequip all", "if(ev.key==='u' || ev.key==='U') (window as any).game?.unequipAll?.()"],
  ["sidebar stat: visible enemies", "Visible Enemies"],
  ["sidebar stat: enemies left", "Enemies Left"],
  ["sidebar stat: stairs visible", "Stairs"],
  ["sidebar stat: merchant proximity", "Merchant"],
  ["sidebar stat: visible ranged", "Visible Ranged"],
  ["sidebar stat: ranged in range", "Ranged In Range"],
  ["sidebar stat: visible elites", "Visible Elites"],
  ["sidebar stat: visible boss hp", "Boss HP"],
  ["sidebar stat: boss charge readiness", "Boss Charge"],
  ["sidebar stat: boss charge countdown", "Boss CD"],
  ["sidebar stat: essence", "Essence"],
  ["sidebar stat: spirits", "Spirits"],
  ["spirit panel header", "Spirits</h3>"],
  ["spirit panel implant action", "Implant"],
  ["spirit panel blocked reason inline", "Major slots full"],
  ["merchant shop header", "Merchant"],
  ["essence shop pity ready label", "• Pity Ready"],
  ["essence shop reroll button", "Reroll ("],
  ["merchant gating helper", "const merchantNearby = useMemo(()=>{"],
  ["merchant gating buy label", "Need Merchant"],
  ["merchant guidance text", "Find and stand next to the Merchant to access essence offers."],
  ["merchant blocked status copy", "Move next to the Merchant to buy."],
  ["shop spirit bonus vector preview", "ATK+{o.core?.bonuses?.atk||0} DEF+{o.core?.bonuses?.def||0} HP+{o.core?.bonuses?.hp||0} DEX+{o.core?.bonuses?.dex||0}"],
  ["sidebar stat: current modifier", "Mod<b>{snapshot?.floorModifier ?? 'none'}</b>"],
  ["sidebar stat: current boss floor", "Boss Floor"],
  ["sidebar stat: boss alive", "Boss Alive"],
  ["sidebar stat: next modifier", "Next Mod"],
  ["sidebar stat: next boss", "Next Boss"],
  ["sidebar stat: danger label", "Danger"],
  ["sidebar stat: pace label", "Pace"],
  ["sidebar stat: streak to loot", "Streak→Loot"],
  ["sidebar stat: score multiplier", "Score x"],
  ["sidebar stat: clear reward preview", "Clear Reward"],
  ["hud secondary stats toggle label", "More Stats"],
  ["danger model includes ranged in-range weighting", "const rangedInRange = (kind==='spitter' && d>1 && d<=5) || (kind==='sentinel' && d>1 && d<=2)"],
  ["inventory section renamed", "<I src={treasureIcon}/>Inventory"],
  ["inventory quick auto-equip button", "Auto Equip"],
  ["inventory quick unequip-all button", "Unequip All"],
  ["inventory quick sort button", "Sort"],
  ["inventory per-item unequip button", "Unequip"],
  ["inventory delta compare label", "Δ vs equipped:"],
  ["skills section header", "<I src={bootsIcon}/>Skills"],
  ["help copy points to skills panel", "Class skills: use the Skills panel"],
  ["app handles modifier hints", "if(e.type==='modifier_hint' && e.payload?.text) setStatus(String(e.payload.text))"],
  ["floor brief status includes comp counts", "monsters (${e.payload?.ranged ?? '?'} ranged, ${e.payload?.elites ?? '?'} elites)"],
  ["stairs status previews next floor", "setStatus(`Stairs found. Next: floor ${nextFloor ?? '?'}, ${nextMod}, ${nextBoss}.`)"],
]

const failures = checks.filter(([, needle]) => !src.includes(needle))

const mountChecks = [
  ["mount helper: float numbers from url", "function getFloatNumbersFromUrl(){"],
  ["mount helper: visual preset from url", "function getVisualPresetFromUrl(): VisualPreset"],
  ["mount visual preset default readable", "return p.get('contrast') === '0' ? 'normal' : 'readable'"],
  ["mount flag: showDamageNumbers", "const showDamageNumbers = getFloatNumbersFromUrl()"],
  ["boss bar phase marker", "const phase = ratio > 0.66 ? 'PHASE I' : ratio > 0.33 ? 'PHASE II' : 'PHASE III'"],
  ["boss intro title card", "showBossIntro('BOSS ENCOUNTER')"],
  ["boss charge ring pulse telegraph", "const ring = sc.add.circle(boss.x, boss.y, tileSize*0.45, 0xff6a6a, 0.14).setDepth(372)"],
  ["boss slam impact decal", "const impact = sc.add.circle(boss.x, boss.y, tileSize*0.35, 0xffb07a, 0.22).setDepth(371)"],
  ["enemy hp bar store tracks last hp", "const hpBars: Record<string, {bg:any, fg:any, lastHp?:number}> = {}"],
  ["damage numbers conditional toggle", "if(showDamageNumbers && Number.isFinite(e.payload?.damage) && e.payload.damage>0) fxDamageNumber(to, e.payload.damage, e.payload.target==='p')"],
  ["fov hidden floor fully dark", "const floorHiddenAlpha = 0"],
  ["fov hidden wall fully dark", "const wallHiddenAlpha = 0"],
  ["deterministic state bootstrap rebuild", "if(st) rebuildMapAndEntities(st)"],
  ["floor event triggers deterministic rebuild", "} else if(e.type==='floor'){"],
  ["mount exposes auto-equip api", "autoEquipBest: ()=> eng.autoEquipBest()"],
  ["mount exposes unequip api", "unequipInventoryIndex: (index:number)=> eng.unequipInventoryIndex(index)"],
  ["mount exposes unequip-all api", "unequipAll: ()=> eng.unequipAll()"],
  ["mount exposes sort api", "sortInventory: ()=> eng.sortInventory()"],
  ["mount exposes spirit equip api", "equipSpiritCore: (index:number)=> eng.equipSpiritCore(index)"],
  ["mount exposes spirit unequip api", "unequipSpiritCore: (index:number)=> eng.unequipSpiritCore(index)"],
  ["mount exposes shop buy api", "buyShopOffer: (index:number)=> eng.buyShopOffer(index)"],
  ["mount exposes shop reroll api", "rerollShopOffers: ()=> eng.rerollShopOffers()"],
]
const mountFailures = mountChecks.filter(([, needle]) => !mountSrc.includes(needle))

const engineChecks = [
  ["starting gear helper exists", "private buildStartingGear(): GeneratedItem[]"],
  ["knight starts with short sword", "name:'Short Sword'"],
  ["rogue starts with dagger", "name:'Rogue Dagger'"],
  ["starting gear applied on initial floor", "for(const gear of this.buildStartingGear()) this.equipGear(gear, player)"],
  ["base vision radius", "const radius = 8"],
  ["ambush modifier exists", "if(floor % 5 === 0) return 'ambush'"],
  ["ambush threat cap bonus", "const threatCap = 8 + this.floor * 1.8 + (this.floorModifier==='ambush' ? 1.2 : 0)"],
  ["ambush closer spawn distance", "const minDist = this.floorModifier==='ambush'"],
  ["scarce-potions compensation chest", "if(this.floorModifier==='scarce-potions') this.spawnItem(`i${this.floor}-cache1`,'chest')"],
  ["ambush template branch", "if(this.floorModifier==='ambush'){"],
  ["high-floor encounter template branch", "if(this.floor >= 4){"],
  ["high-floor crossfire placement", "if(rangedA) this.tryRepositionMonster(rangedA, {x:anchor.x+2,y:anchor.y-1}, 5)"],
  ["modifier hint event emitted", "if(modHint) this.emit({tick:this.tick,type:'modifier_hint'"],
  ["floor brief includes ranged+elite counts", "payload:{floor:this.floor,modifier:this.floorModifier,monsters:monstersNow,items:itemsNow,ranged:rangedNow,elites:eliteNow}"],
  ["stairs event includes next-floor preview", "this.emit({tick:this.tick,type:'stairs_spawned',payload:{floor:this.floor,nextFloor,nextModifier,nextBoss}})"],
  ["ambush clear reward includes potion", "if(this.floorModifier==='ambush') this.spawnItem(`i${this.floor}-ambush-recover-${this.tick}`,'potion')"],
  ["brute-heavy clear reward includes gear", "if(this.floorModifier==='brute-heavy') this.spawnItem(`i${this.floor}-brute-reward-${this.tick}`,'gear')"],
  ["scarce-potions clear reward includes elixir", "if(this.floorModifier==='scarce-potions') this.spawnItem(`i${this.floor}-scarce-reward-${this.tick}`,'elixir')"],
  ["swarm clear reward includes bomb", "if(this.floorModifier==='swarm') this.spawnItem(`i${this.floor}-swarm-reward-${this.tick}`,'bomb')"],
  ["ambush increases AI sense radius", "this.floorModifier==='ambush' ? 10 : this.floorModifier==='swarm' ? 9 : 7"],
  ["ambush buffs spitter base damage", "const spitBase = this.floorModifier==='ambush' ? 2 : 1"],
  ["ambush buffs sentinel zap base damage", "const zapBase = this.floorModifier==='ambush' ? 2 : 1"],
  ["ambush opening fairness window", "const ambushOpening = this.floorModifier==='ambush' && (this.tick - this.floorStartTick) <= 2"],
  ["ambush ranged hit cap", "if(ambushOpening && ambushRangedHitsThisTurn>=1){"],
  ["ambush hold-fire lateral movement", "const lateralA = {x:m.pos.x + 1, y:m.pos.y}"],
  ["ambush spawn LOS audit", "if(d<=5 && this.hasLineOfSight(m.pos, player.pos)){"],
  ["ambush enforces ranged threat", "private enforceAmbushRangedThreat(){"],
  ["ambush ranged threat called before template", "this.enforceAmbushRangedThreat()"],
  ["engine auto-equip helper", "autoEquipBest(){"],
  ["engine unequip helper", "unequipInventoryIndex(index:number){"],
  ["engine unequip-all helper", "unequipAll(){"],
  ["engine sort helper", "sortInventory(){"],
  ["engine spirit modifier roll helper", "private rollSpiritModifier(): SpiritModifier {"],
  ["spirit modifier rebalance comment", "Modifier rebalance pass: keep total value close while changing shape."],
  ["engine spirit loot drop helper", "private maybeDropSpiritLoot(dead: Entity){"],
  ["engine spirit equip method", "equipSpiritCore(index:number){"],
  ["engine spirit unequip method", "unequipSpiritCore(index:number){"],
  ["engine spirit blocked reason state", "lastSpiritEquipBlockedReason"],
  ["engine shop refresh helper", "private refreshShopOffers(){"],
  ["engine spirit pity trigger", "const pityReady = this.spiritDryFloors >= 2"],
  ["engine shop buy method", "buyShopOffer(index:number){"],
  ["engine shop reroll method", "rerollShopOffers(){"],
  ["engine merchant proximity helper", "private isMerchantNearby(range=1){"],
  ["engine floor spawns merchant", "this.spawnItem(`i${this.floor}-merchant`,'merchant')"],
  ["engine shop buy blocked when merchant far", "shop_buy_blocked',payload:{reason:'merchant_far'"],
  ["engine shop reroll blocked when merchant far", "shop_reroll_blocked',payload:{reason:'merchant_far'"],
  ["engine score helper", "private scoreForKill(kind:string|undefined){"],
  ["ambush score multiplier", "this.floorModifier==='ambush' ? 1.2 : this.floorModifier==='brute-heavy' ? 1.1 : 1"],
]
const engineFailures = engineChecks.filter(([, needle]) => !engineSrc.includes(needle))

const absentChecks = [
  ["legacy threat intel label removed", "Threat Intel"],
  ["legacy run progress label removed", "Run Progress"],
  ["legacy nearby stat removed", "Nearby<b>"],
  ["legacy equipment header renamed", "/>Equipment</h3>"],
  ["legacy direct guard hotkey removed", "if(ev.key==='g' || ev.key==='G') g.step({type:'guard'})"],
  ["legacy direct backstep hotkey removed", "if(ev.key==='q' || ev.key==='Q') castOrArm('backstep')"],
  ["legacy direct bash hotkey removed", "if(ev.key==='b' || ev.key==='B') castOrArm('bash')"],
  ["legacy sidebar title removed", "className='dq-title'"],
  ["legacy sidebar objective block removed", "Objective: {objectiveText}"],
  ["player halo removed", "playerHalo"],
  ["legacy run-complete floor-cap copy removed", "Use stairs to complete the run."],
]
const absentFailures = absentChecks.filter(([, needle]) => src.includes(needle))

const legacySeedExpr = "Math.floor(Math.random()*1_000_000)+1"
const seedExprCount = src.split(legacySeedExpr).length - 1
const seedExprGuardFailed = seedExprCount !== 1

if (failures.length || mountFailures.length || engineFailures.length || absentFailures.length || seedExprGuardFailed) {
  console.error('UI smoke checks failed:')
  for (const [name] of failures) console.error(`- missing: ${name}`)
  for (const [name] of mountFailures) console.error(`- mount missing: ${name}`)
  for (const [name] of engineFailures) console.error(`- engine missing: ${name}`)
  for (const [name] of absentFailures) console.error(`- should be removed: ${name}`)
  if (seedExprGuardFailed) console.error(`- guard: expected exactly 1 random-seed expression (in helper), found ${seedExprCount}`)
  process.exit(1)
}

console.log(`UI smoke checks passed (${checks.length + mountChecks.length + engineChecks.length + absentChecks.length} checks, 1 guard).`)
